### ISSUE TITLE
Test_FeatureAdder.testTooManyFeatures and Test_FeatureAdder.testNoFeatures fail

### ISSUE THREAD

**Issue by bamueh** [acorg/dark-matter#327]
The two tests above fail with the following error:

```sh
Traceback (most recent call last):
  File "/Users/barbara/dark-matter/dark-matter/test/test_features.py", line 357, in testNoFeatures
    transform=ANY, fontsize=20)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/unittest/mock.py", line 790, in assert_called_with
    if expected != actual:
  File "/Users/barbara/.virtualenvs/dm35/lib/python3.5/site-packages/matplotlib/transforms.py", line 1562, in __eq__
    if other.is_affine:
AttributeError: '_ANY' object has no attribute 'is_affine'
```

Can you reproduce that, or is something weird with my matplotlib?

**Comment by terrycojones** [comment]
As discussed in IRC, this is fixed in a later version (1.4.3) of matplotlib.
