### ISSUE TITLE
noninteractive-alignment-panel.py can throw a unicode decode error

### ISSUE THREAD

**Issue by terrycojones** [acorg/dark-matter#438]
This from an Eske Willerslev run. A `UnicodeDecodeError` bubbles up from the primeval bog:

```sh
$ noninteractive-alignment-panel.py \
--matcher diamond \
--outputDir out \
--json ../04-diamond/ESW_ELCK_DA74_E1_L2_S1_CGCTAT_L006_R1_001.json.bz2 \
--json ../04-diamond/ESW_ELCK_DA74_E1_L2_S1_CGCTAT_L006_R1_002.json.bz2 \
--json ../04-diamond/ESW_ELCK_DA74_E1_L2_S1_CGCTAT_L006_R1_003.json.bz2 \
--json ../04-diamond/ESW_ELCK_DA74_E1_L2_S1_CGCTAT_L006_R1_004.json.bz2 \
--json ../04-diamond/ESW_ELCK_DA74_E1_L2_S1_CGCTAT_L006_R1_005.json.bz2 \
--json ../04-diamond/ESW_ELCK_DA74_E1_L2_S1_CGCTAT_L006_R1_006.json.bz2 \
--json ../04-diamond/ESW_ELCK_DA74_E1_L2_S1_CGCTAT_L007_R1_001.json.bz2 \
--json ../04-diamond/ESW_ELCK_DA74_E1_L2_S1_CGCTAT_L007_R1_002.json.bz2 \
--json ../04-diamond/ESW_ELCK_DA74_E1_L2_S1_CGCTAT_L007_R1_003.json.bz2 \
--json ../04-diamond/ESW_ELCK_DA74_E1_L2_S1_CGCTAT_L007_R1_004.json.bz2 \
--json ../04-diamond/ESW_ELCK_DA74_E1_L2_S1_CGCTAT_L007_R1_005.json.bz2 \
--json ../04-diamond/ESW_ELCK_DA74_E1_L2_S1_CGCTAT_L008_R1_001.json.bz2 \
--json ../04-diamond/ESW_ELCK_DA74_E1_L2_S1_CGCTAT_L008_R1_002.json.bz2 \
--json ../04-diamond/ESW_ELCK_DA74_E1_L2_S1_CGCTAT_L008_R1_003.json.bz2 \
--json ../04-diamond/ESW_ELCK_DA74_E1_L2_S1_CGCTAT_L008_R1_004.json.bz2 \
--json ../04-diamond/ESW_ELCK_DA74_E1_L2_S1_CGCTAT_L008_R1_005.json.bz2 \
--fastq ../03-find-unmapped/ESW_ELCK_DA74_E1_L2_S1_CGCTAT_L006_R1_001-unmapped.fastq.gz \
--fastq ../03-find-unmapped/ESW_ELCK_DA74_E1_L2_S1_CGCTAT_L006_R1_002-unmapped.fastq.gz \
--fastq ../03-find-unmapped/ESW_ELCK_DA74_E1_L2_S1_CGCTAT_L006_R1_003-unmapped.fastq.gz \
--fastq ../03-find-unmapped/ESW_ELCK_DA74_E1_L2_S1_CGCTAT_L006_R1_004-unmapped.fastq.gz \
--fastq ../03-find-unmapped/ESW_ELCK_DA74_E1_L2_S1_CGCTAT_L006_R1_005-unmapped.fastq.gz \
--fastq ../03-find-unmapped/ESW_ELCK_DA74_E1_L2_S1_CGCTAT_L006_R1_006-unmapped.fastq.gz \
--fastq ../03-find-unmapped/ESW_ELCK_DA74_E1_L2_S1_CGCTAT_L007_R1_001-unmapped.fastq.gz \
--fastq ../03-find-unmapped/ESW_ELCK_DA74_E1_L2_S1_CGCTAT_L007_R1_002-unmapped.fastq.gz \
--fastq ../03-find-unmapped/ESW_ELCK_DA74_E1_L2_S1_CGCTAT_L007_R1_003-unmapped.fastq.gz \
--fastq ../03-find-unmapped/ESW_ELCK_DA74_E1_L2_S1_CGCTAT_L007_R1_004-unmapped.fastq.gz \
--fastq ../03-find-unmapped/ESW_ELCK_DA74_E1_L2_S1_CGCTAT_L007_R1_005-unmapped.fastq.gz \
--fastq ../03-find-unmapped/ESW_ELCK_DA74_E1_L2_S1_CGCTAT_L008_R1_001-unmapped.fastq.gz \
--fastq ../03-find-unmapped/ESW_ELCK_DA74_E1_L2_S1_CGCTAT_L008_R1_002-unmapped.fastq.gz \
--fastq ../03-find-unmapped/ESW_ELCK_DA74_E1_L2_S1_CGCTAT_L008_R1_003-unmapped.fastq.gz \
--fastq ../03-find-unmapped/ESW_ELCK_DA74_E1_L2_S1_CGCTAT_L008_R1_004-unmapped.fastq.gz \
--fastq ../03-find-unmapped/ESW_ELCK_DA74_E1_L2_S1_CGCTAT_L008_R1_005-unmapped.fastq.gz \
--withScoreBetterThan 40 \
--maxTitles 200 \
--diamondDatabaseFilename /home/tcj25/scratch/root/share/ncbi/diamond-dbs/viral.nonredundant_protein.protein.dmnd
Found 1 interesting title.
Sun Oct 30 21:16:31 2016: Plotting 1 titles in 1x5 grid, sorted on maxScore
0: gi|769275405|ref|WP_045009361.1| DNA adenine methylase [Clostridium phage phiSM101] http://www.ncbi.nlm.nih.gov/nuccore/WP_045009361
Traceback (most recent call last):
  File "/scratch/tcj25/root/.virtualenvs/35/bin/noninteractive-alignment-panel.py", line 291, in <module>
    logLinearXAxis=args.logLinearXAxis, logBase=args.logBase)
  File "/scratch/tcj25/root/.virtualenvs/35/lib/python3.5/site-packages/dark/graphics.py", line 559, in alignmentPanel
    showOrfs=True)
  File "/scratch/tcj25/root/.virtualenvs/35/lib/python3.5/site-packages/dark/graphics.py", line 174, in alignmentGraph
    sequence = readsAlignments.getSubjectSequence(title)
  File "/scratch/tcj25/root/.virtualenvs/35/lib/python3.5/site-packages/dark/diamond/alignments.py", line 127, in getSubjectSequence
    for read in FastaReads(self._databaseFilename, readClass=AARead):
  File "/scratch/tcj25/root/.virtualenvs/35/lib/python3.5/site-packages/dark/reads.py", line 705, in __iter__
    for read in chain(self.iter(), self.additionalReads):
  File "/scratch/tcj25/root/.virtualenvs/35/lib/python3.5/site-packages/dark/fasta.py", line 122, in iter
    for seq in SeqIO.parse(fp, 'fasta'):
  File "/scratch/tcj25/root/.virtualenvs/35/lib/python3.5/site-packages/Bio/SeqIO/__init__.py", line 600, in parse
    for r in i:
  File "/scratch/tcj25/root/.virtualenvs/35/lib/python3.5/site-packages/Bio/SeqIO/FastaIO.py", line 122, in FastaIterator
    for title, sequence in SimpleFastaParser(handle):
  File "/scratch/tcj25/root/.virtualenvs/35/lib/python3.5/site-packages/Bio/SeqIO/FastaIO.py", line 43, in SimpleFastaParser
    line = handle.readline()
  File "/scratch/tcj25/root/.virtualenvs/35/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xee in position 2: invalid continuation byte
```

**Comment by terrycojones** [comment]
This was due to a non-FASTA file being passed as the `--diamondDatabaseFilename` argument (since renamed to `--diamondDatabaseFastaFilename` btw). I'm not sure that we should do anything here. Probably `SeqIO.parse` should say something more useful.
