### ISSUE TITLE
proteins-to-pathogens.py can somehow raise on an attempted float conversion

### ISSUE THREAD

**Issue by terrycojones** [acorg/dark-matter#525]
Not sure how this could be happening yet...

```sh
$ find . -name summary-bacteria | proteins-to-pathogens.py \
    --format fastq \
    --html \
    --pathogenPanelFilename bacteria.png \
    --sampleNameRegex '/(\d)/' \
    --proteinFastaFilename $HOME/scratch/root/share/ncbi/bacterial-refseq/20170421/bacteria.nonredundant_protein.fasta \
    --minProteinFraction 0.1 \
    --pathogenType bacterial \
    > bacteria.html

Traceback (most recent call last):
  File "/scratch/tcj25/root/.virtualenvs/35/bin/proteins-to-pathogens.py", line 130, in <module>
    grouper.addFile(filename, fp)
  File "/scratch/tcj25/root/.virtualenvs/35/lib/python3.5/site-packages/dark/proteins.py", line 305, in addFile
    'bestScore': float(bestScore),
ValueError: could not convert string to float: 'from'
make: *** [bacteria.html] Error 1
```

**Comment by terrycojones** [comment]
Ah, this is not a bug in the code, it's a result of passing the `summary-bacteria` files into `proteins-to-pathogens.py`. The `summary-proteins` files should be being passed. Closing.
